import { Footer } from "@/app/components/Footer";
import { Header } from "@/app/components/Header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Web3 TD1",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div
          style={{
            height: "calc(100vh - 100px)",
            overflowY: "auto",
            width: "100%",
          }}
        >
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
